services:
  app:
    build: .
    ports:
      - "${UI_PORT:-8169}:5001"
    environment:
      - NODE_ENV=production
      - APP_PORT=${APP_PORT:-5001}
    networks:
      - app_net

networks:
  app_net:
    driver: bridge
