services:
  app:
    image: whatsback-web
    build: .
    container_name: whatsback-app-provider
    ports:
      - "${UI_PORT:-8169}:5001"
    environment:
      - NODE_ENV=production
      - APP_PORT=${APP_PORT:-5001}
      - DB_PATH=/data/database.sqlite
    volumes:
      - db-data:/data
    networks:
      app_net:
        aliases:
          - whatsback-app-provider
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:$$APP_PORT/health || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 5
      start_period: 30s

  cronjob:
    image: whatsback-web
    container_name: whatsback-app-cronjob
    environment:
      - NODE_ENV=production
      - APP_HOST=app
      - DB_PATH=/data/database.sqlite
    volumes:
      - db-data:/data
    command: sh -c "./wait-for app:5001 -t 120 -- node cronjob.js"
    networks:
      - app_net
    depends_on:
      app:
        condition: service_healthy

networks:
  app_net:
    driver: bridge

volumes:
  db-data: